SELECT ID, PT_NOME, DESCRICAO, PALAVRAS_CHAVE, DATA_INICIO, DATA_FINAL FROM CHAMADOS c ORDER BY 1 DESC;	

SELECT * FROM DESVIOS d ORDER BY 1 DESC;

SELECT * FROM CHAMADOS c ORDER BY 1 DESC; 

SELECT * FROM FEATURE_CRIADAS fc ORDER BY 1 DESC;

INSERT INTO FEATURE_CRIADAS (NAME_FEATURE, NAME_BRANCH, SHA_ORIGEM, REGEX_SEARCH, DESC_PT, NAME_PT, TYPE_FEATURE, DATETIME_FIELD) 
VALUES ('PT_550463_MR', 'V559', 'ebc5d8a6', 'Login By Ticket', ' LoginByTicket (Utilizando Direct)', '550463', 'MR', '2020-06-18 19:07:00.000')

/***************************************************************************************************************************/

SELECT * FROM FEATURE_CRIADAS fc WHERE REGEX_SEARCH LIKE '%823321%'
SELECT * FROM FEATURE_CRIADAS fc WHERE NAME_PT = 823321

UPDATE FEATURE_CRIADAS fc SET LINK_MR = 'https://gitlab.com/apdata/global-antares/-/merge_requests/2983' WHERE SHA_ORIGEM = '3e07dfe4f21'
 


